spring.application.name=Flexidle-SB
spring.datasource.url=jdbc:postgresql://postgres.mau.se:55432/ar5917
spring.datasource.username=ar5917
spring.datasource.password=f9ww8zcf
spring.datasource.driver-class-name=org.postgresql.Driver